# Default voice
# Will be used if latin or cyrillic voices are not set
voice=ru-RU-DmitryNeural

# Cyrillic voice
#cyrillic-voice=ru-RU-DmitryNeural

# Latin voice
#latin-voice=Microsoft Ava (Natural HD) - English (United States)

# Speech rate
rate=100

# Pitch
pitch=0

# Volume
volume=0
